package ai.arturxdroid.mushroomtify

object Constants {

    public val LABELS_LIST = arrayListOf<String>(
        "amanita muscaria",
        "amanita pantherina",
        "amanita phalloides",
        "amanita verna",
        "armillaria gallica",
        "armillaria mellea",
        "boletus betulicola",
        "boletus edulis",
        "boletus pinicola",
        "boletus pinophilusm",
        "boletus satanas",
        "cantharellus cibarius",
        "corpinellus micaceus",
        "fomes fomentarius",
        "fomitopsis pinicola",
        "galerina marginata",
        "ganoderma pfeifferi",
        "hypholoma fasciculare",
        "lactarius delicious",
        "lactarius deterrimus",
        "leccinum melaneum",
        "leccinum scabrum",
        "leccinum variicolor",
        "leccinum versipelle",
        "leccinum vulpinium",
        "mycena galericulata",
        "pluteus cervinus",
        "psathyrella candolleana",
        "russula aeruginea",
        "russula claroflava",
        "russula vesca",
        "russula xerampelina",
        "suillus flavidus",
        "suillus granulatus",
        "suillus grevillei",
        "suillus luteus",
        "trametes versicolor",
        "tricholoma scalpturatum",
        "xerocomellus chrysenteron"
    )
}